### ISSUE TITLE
Too many files open

### ISSUE THREAD

**Issue by typemismatch** [ConcurrenyLabs/mqtt-locust#1]
I get a Too many files open with 125/5 test run. Outside of that is has been working great.

**Comment by concurrencylabs** [comment]
Nice to hear it's been useful. I got the same error at some point, when I increased the number of users (I don't remember the exact number, though). It got fixed by increasing the size of my EC2 instance to a t2.medium or t2.large. This is for the instance that is running Locust and generating load. What infrastructure are you using for this test?

**Comment by typemismatch** [comment]
I'm running it on an m4.large - I just spun up a bunch of them to get around that issue. I'll try a bigger size and see if it helps. Next I'm going to wrap this into a docker image and then run it on a cluster :)

**Comment by kapilt** [comment]
too many open files is an os configuration item.

**Comment by concurrencylabs** [comment]
I will close this issue, you can refer to this issue in the Locust repo.

https://github.com/locustio/locust/issues/92
